### PR TITLE
Create website header

### PR DESCRIPTION
**Pull request by Benmuiruri**
Hello @Regiss05 
I have created the Website header 

- Added the header logo 
- Added the Navigation links
- Styled the Header 

This PR is for the issue no  #27

### CODE REVIEW

**Review by Regiss05 — CHANGES_REQUESTED** [review]
Hey @Benmuiruri✋🏻
The header is actually done. Great Job!

- [ ] Please fix linters

**Review by Regiss05 — CHANGES_REQUESTED** [review]
Hey @Benmuiruri✋🏻
The header is actually done. Great Job!

- [ ] Please fix linters

**Comment by Benmuiruri** [comment]
I have fixed the linter

**Review by Regiss05 — APPROVED** [review]
Hi @Benmuiruri 

There is nothing else to say. You can merge
Congratilations

**Pull request merged**
